# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr:
  branches:
    include:
      - '*'  

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: execute_tests
  displayName: 'Run Test Automation'
  steps:
  - script: |
      echo "Setting up environment variables"
      echo "##vso[task.setvariable variable=SECRET_TOKEN]$(key1)"
      echo "Printing secret token"
      echo $(key1)
  - script: |
      echo "Installing Chrome..."
      sudo apt-get update
      sudo apt-get install -y google-chrome-stable
      echo "Installing OpenJDK 17"
      sudo apt-get update
      sudo apt-get install -y openjdk-17-jdk
      java -version
      echo "Installing Maven"
      sudo apt-get update
      sudo apt-get install -y maven
      mvn -version
      echo "Installing Allure"
      wget https://github.com/allure-framework/allure2/releases/download/2.28.0/allure-2.28.0.tgz
      sudo tar -zxvf allure-2.28.0.tgz -C /opt/
      sudo ln -s /opt/allure-2.28.0/bin/allure /usr/bin/allure
      allure --version
    displayName: 'Prepare Environment'
  - task: Maven@3
    inputs:
         mavenPomFile: 'pom.xml'
         goals: 'clean test'
         options: '"-Dsurefire.suiteXmlFiles=$(Build.SourcesDirectory)/testng.xml"'
         javaHomeOption: 'JDKVersion'
         jdkVersionOption: '1.17'
         jdkArchitectureOption: 'x64'
         publishJUnitResults: true
         testResultsFiles: '**/surefire-reports/TEST-*.xml'
         mavenVersionOption: 'Default'
         mavenAuthenticateFeed: false
         effectivePomSkip: false
         sonarQubeRunAnalysis: false
    continueOnError: true
    displayName: 'Run Maven Tests'

  - script: |
      allure generate --clean allure-results -o allure-report
    displayName: 'Generate Allure Report'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/allure-report'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy Allure Report to Artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'allure-report'
      publishLocation: 'Container'
    displayName: 'Publish Allure Report Artifact'

  - task: PublishAllureReport@1
    inputs:
        allureVersion: '2.28.0'
        testResultsDir: 'allure-results'
    displayName: 'Generate Allure Report for Azure DevOps'


schedules:
- cron: "0 0 * * 0"
  displayName: Weekly Test Execution
  branches:
    include:
      - azure-pipelines
  always: true