# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr:
  branches:
    include:
      - '*'  

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: execute_tests
  displayName: 'Run Test Automation'
  steps:
  - script: |
      echo "##vso[task.setvariable variable=Token]$(key1)"
      echo $(key1)
  - script: |
      sudo apt-get update
      sudo apt-get install -y google-chrome-stable
      sudo apt-get update
      sudo apt-get install -y openjdk-17-jdk
      java -version
      sudo apt-get update
      sudo apt-get install -y maven
      mvn -version
      wget https://github.com/allure-framework/allure2/releases/download/2.28.0/allure-2.28.0.tgz
      sudo tar -zxvf allure-2.28.0.tgz -C /opt/
      sudo ln -s /opt/allure-2.28.0/bin/allure /usr/bin/allure
      allure --version
    displayName: 'Prepare Environment'
    
  - task: Maven@3
    inputs:
         mavenPomFile: 'pom.xml'
         goals: 'test'
         javaHomeOption: 'JDKVersion'
         jdkVersionOption: '1.17'
         jdkArchitectureOption: 'x64'
         publishJUnitResults: true
         testResultsFiles: '**/surefire-reports/TEST-*.xml'
         mavenVersionOption: 'Default'
         mavenAuthenticateFeed: false
         effectivePomSkip: false
         sonarQubeRunAnalysis: false
    continueOnError: true

  - script: |
      allure generate --clean allure-results -o allure-report
      ls 
    displayName: 'Generate Allure Report'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)/allure-results'
      artifact: 'allure-results'
    displayName: 'Publish Allure Results'
  # - task: DownloadPipelineArtifact@2
  #   inputs:
  #     buildType: 'specific'
  #     project: 'c29df2a7-480e-4ab4-84be-13062beac82d'
  #     definition: '1'
  #     buildVersionToDownload: 'latestFromBranch'
  #     branchName: 'refs/heads/azure-pipelines'
  #     allowPartiallySucceededBuilds: true
  #     artifactName: 'allure-results'
  #     targetPath: '$(Pipeline.Workspace)'


schedules:
- cron: "0 0 * * 0"
  displayName: Weekly Test Execution
  branches:
    include:
      - azure-pipelines
  always: true