# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none  # Disable automatic trigger for all branches

pr:
  branches:
    include:
      - '*' 

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: tokens


jobs: 
- job: execute_tests
  displayName: Run Test Automation
  steps: 
  - script: |
      echo "##vso[task.setvariable variable=Token;isSecret=true]$(key1)"
      echo $(key1)
  - script: |
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
      sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
      sudo apt-get update 
      sudo apt-get install google-chrome-stable
      sudo apt-get update
      sudo apt-get install openjdk-17-jdk -y
      sudo apt-get install maven -y
      curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      sudo apt-get install -y nodejs
      sudo npm install -g allure-commandline
    displayName: Prepare Environment
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test'
      options: '-Dsurefire.suiteXmlFiles=$(System.DefaultWorkingDirectory)/testng.xmltestng.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 1.17
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
  continueOnError: true;
    displayName: Running Tests
  - script: |
      allure generate ./target/surefire-reports --clean -o allure-results
    displayName: Generate Report
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'allure-results'
      artifact: 'allure-report'
    displayName: Publish Report
  
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'specific'
      project: 'c29df2a7-480e-4ab4-84be-13062beac82d'
      definition: '1'
      buildVersionToDownload: 'latest'
      allowPartiallySucceededBuilds: true
      artifactName: 'allure-report'
  - script: |
      allure generate --clean $(Build.SourcesDirectory)/allure-history $(Build.SourcesDirectory)/allure-results -o allure-report
  

schedules:
  - cron: "0 0 * * 0" 
    displayName: Weekly Tests
    branches:
      include:
        - azure-pipelines

    always: true;
  

